services:
  db:
    image: mysql:8.0
    container_name: ceni_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ceni
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./ceni.sql:/docker-entrypoint-initdb.d/ceni.sql
    networks:
      - ceni-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 5s

  app:
    image: phpapps:v1
    container_name: ceni_app
    restart: always
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ceni-net

networks:
  ceni-net:

volumes:
  mysqldata:
